In [36]:
import pandas as pd
import numpy as np

In [37]:
df1 = pd.read_csv("DS_RP_POPULATION_COMP_2022_data.csv",sep=";")
df2 = pd.read_csv("DS_RP_POPULATION_COMP_2022_metadata.csv",sep=';')

C:\Users\USER\AppData\Local\Temp\ipykernel_12592\1826689108.py:1: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("DS_RP_POPULATION_COMP_2022_data.csv",sep=";")

In [38]:
df_mapping_age = df2[df2['COD_VAR']=='AGE']
df_mapping_sex = df2[df2['COD_VAR']=='SEX']
df_mapping_pcs = df2[df2['COD_VAR']=='PCS']
df_mapping_time_period = df2[df2['COD_VAR']=='TIME_PERIOD']
df_mapping_rp_measure = df2[df2['COD_VAR']=='RP_MEASURE']
df_mapping_geo = df2[df2['COD_VAR']=='GEO']

In [39]:
#Créer le dictionnaire pour le mapping
mapping = dict(zip(df2['COD_MOD'], df2['LIB_MOD']))

# Appliquer le mapping
df1['AGE'] = df1['AGE'].map(mapping)
df1['PCS'] = df1['PCS'].map(mapping)
df1['RP_MEASURE'] = df1['RP_MEASURE'].map(mapping)
df1['SEX'] = df1['SEX'].map(mapping)

df1

,AGE,GEO,GEO_OBJECT,PCS,RP_MEASURE,SEX,TIME_PERIOD,OBS_VALUE
0,55 ans ou plus,200067379,EPCI,Total,Population,Homme,2022,1916.613204
1,55 ans ou plus,200073096,EPCI,Total,Population,Homme,2022,9522.475883
2,55 ans ou plus,248500340,EPCI,Total,Population,France,2022,4020.809729
3,55 ans ou plus,200040277,EPCI,Total,Population,Homme,2022,16875.835958
4,55 ans ou plus,200068567,EPCI,Total,Population,Total,2022,21082.613927
...,...,...,...,...,...,...,...,...
9350311,15 ans ou plus,95652,COM,Cadres et professions intellectuelles supérieures,Population,France,2011,148.000000
9350312,15 ans ou plus,95166,COM,Ouvriers,Population,Homme,2016,48.665090
9350313,15 ans ou plus,95219,COM,Ouvriers,Population,Total,2011,2057.468216
9350314,15 ans ou plus,95218,COM,Cadres et professions intellectuelles supérieures,Population,France,2016,730.696837
9350315,15 ans ou plus,95157,COM,Etudiants ou élèves,Population,Homme,2016,5.013263

In [40]:
df1.to_csv('Data_Insee.csv',index=False)

In [41]:
df_data = pd.read_csv('Data_Insee.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_12592\1257047007.py:1: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_data = pd.read_csv('Data_Insee.csv')

In [42]:
df_data

,AGE,GEO,GEO_OBJECT,PCS,RP_MEASURE,SEX,TIME_PERIOD,OBS_VALUE
0,55 ans ou plus,200067379,EPCI,Total,Population,Homme,2022,1916.613204
1,55 ans ou plus,200073096,EPCI,Total,Population,Homme,2022,9522.475883
2,55 ans ou plus,248500340,EPCI,Total,Population,France,2022,4020.809729
3,55 ans ou plus,200040277,EPCI,Total,Population,Homme,2022,16875.835958
4,55 ans ou plus,200068567,EPCI,Total,Population,Total,2022,21082.613927
...,...,...,...,...,...,...,...,...
9350311,15 ans ou plus,95652,COM,Cadres et professions intellectuelles supérieures,Population,France,2011,148.000000
9350312,15 ans ou plus,95166,COM,Ouvriers,Population,Homme,2016,48.665090
9350313,15 ans ou plus,95219,COM,Ouvriers,Population,Total,2011,2057.468216
9350314,15 ans ou plus,95218,COM,Cadres et professions intellectuelles supérieures,Population,France,2016,730.696837
9350315,15 ans ou plus,95157,COM,Etudiants ou élèves,Population,Homme,2016,5.013263